# Coin Flips and Die Rolls
Use NumPy to create simulations and compute proportions for the following outcomes. The first one is done for you.

In [1]:
# import numpy
import numpy as np

### 1. Two fair coin flips produce exactly two heads

In [2]:
# simulate 1 million tests of two fair coin flips
tests = np.random.randint(2, size=(int(1e6), 2))
print(tests)
# sums of all tests
test_sums = tests.sum(axis=1)
print(test_sums)

# proportion of tests that produced exactly two heads
(test_sums == 0).mean()

[[0 0]
 [1 1]
 [1 1]
 ...
 [1 0]
 [0 1]
 [0 1]]
[0 2 2 ... 1 1 1]


0.249478

### 2. Three fair coin flips produce exactly one head

In [3]:
# simulate 1 million tests of three fair coin flips
tests = np.random.randint(2, size = (int(1e6), 3))

# sums of all tests
test_sums = tests.sum(axis=1)

# proportion of tests that produced exactly one head
(test_sums==1).mean()

0.374726

### 3. Three biased coin flips with P(H) = 0.6 produce exactly one head

In [4]:
# simulate 1 million tests of three bias coin flips
# hint: use np.random.choice()
tests = np.random.choice([0,1], size = (int(1e6),3), p=[0.6, 0.4])
print(tests)
# sums of all tests
test_sums = tests.sum(axis=1)
print(test_sums)

# proportion of tests that produced exactly one head
(test_sums == 2).mean()


[[0 0 1]
 [1 1 0]
 [0 0 0]
 ...
 [1 0 0]
 [0 1 0]
 [0 1 0]]
[1 2 0 ... 1 1 1]


0.288044

### 4. A die rolls an even number

In [5]:
# simulate 1 million tests of one die roll
tests = np.random.randint(1,7, size = int(1e6))
print(tests)
# proportion of tests that produced an even number

print(((tests == 2)|(tests == 4)|(tests == 6)).mean())


[4 3 3 ... 2 3 2]
0.499892


### 5. Two dice roll a double

In [6]:
# simulate the first million die rolls
first = np.random.randint(1,7, size =  int(1e6))
print(first)
# simulate the second million die rolls
second = np.random.randint(1,7, size = int(1e6))
print(second)
# proportion of tests where the 1st and 2nd die rolled the same number
(first == second).mean()


[3 3 4 ... 2 6 5]
[2 3 2 ... 1 3 6]


0.166765